general:
  name: l2q256_exp_2
  root_dir: null
dset:
  prior_sampler:
    cls: ExpUniformSubPriorSampler
    kwargs:
      params: [
        # d
        [10., 700.],
        [0., 50.],
        # sigma
        [0., 50.],
        [0., 30.],
        [0., 20.],
        # rho
        [5., 20., 0.1, 8.],
        [17., 24., 0.001, 2.],
        [17., 24., 0.001, 2.],
      ]
      logdist: false
      relative_min_bound_width: 1.0e-2
  q_generator:
    cls: ConstantAngle
    kwargs:
      angle_range: [0.05, 2.6, 256]
      wavelength: 0.729322
  intensity_noise:
    cls: BasicExpIntensityNoise
    kwargs:
      relative_errors: [0.05, 0.3]
      abs_errors: 1.0e-8
      consistent_rel_err: false
      logdist: true
      apply_shift: true
      scale_range: [-0.01, 0.01]
  q_noise:
    cls: BasicQNoiseGenerator
    kwargs:
      shift_std: 5.0e-4
      noise_std: [0., 0.001]
model:
  encoder:
    cls: SubPriorConvFCEncoder
    pretrained_name: null
    kwargs:
       hidden_dims: [32, 64, 128, 256, 512]
       latent_dim: 8
       conv_latent_dim: 128
       avpool: 4
       use_batch_norm: true
       in_features: 256
       prior_in_features: 16
       hidden_features: 512
       num_blocks: 2
       pass_bounds: false
       pretrained_conv: null
training:
  num_iterations: 10000
  batch_size: 4096
  lr: 1.0e-3
  update_tqdm_freq: 1
  grad_accumulation_steps: 1
  logger:
    use_neptune: false
  optimizer: AdamW

  callbacks:
    save_best_model:
      enable: true
      freq: 500
slurm:
  time: 04-00:00:00
  partition: upex
  reservation: false
  chdir: '~/maxwell_output'
