general:
  name: multilayer_test_1
  root_dir: null
dset:
  cls: MultilayerDataset
  prior_sampler:
    cls: SimpleMultilayerSampler
    kwargs:
      model_name: model1
      params:
          d_full_rel: [1, 45]
          rel_sigmas: [0, 3]
          d_block: [19, 22]
          s_block_rel: [0.05, 0.1]
          r_block: [2., 10.]
          dr: [1, 10]
          d3_rel: [0, 1]
          s3_rel: [0, 1]
          r3: [2, 24]
          d_sio2: [9, 11]
          s_sio2: [2, 3]
          s_si: [0.9, 1.1]
          r_sio2: [17.6, 17.8]
          r_si: [20., 20.1]
  q_generator:
    cls: ConstantAngle
    kwargs:
      angle_range: [0.05, 2.6, 256]
      wavelength: 0.729322
  intensity_noise:
    cls: BasicExpIntensityNoise
    kwargs:
      relative_errors: [0.05, 0.2]
      abs_errors: 1.0e-10
      consistent_rel_err: false
      logdist: true
      apply_shift: true
      scale_range: [-0.02, 0.02]
  q_noise:
    cls: BasicQNoiseGenerator
    kwargs:
      shift_std: 5.0e-4
      noise_std: [0., 0.001]
model:
  encoder:
    cls: SeqConvFCEncoder
    pretrained_name: null
    kwargs:
       hidden_dims: [32, 64, 128, 256, 512]
       latent_dim: 14
       conv_latent_dim: 128
       avpool: 8
       use_batch_norm: true
       in_features: 256
       hidden_features: 512
       num_blocks: 3
training:
  num_iterations: 10000
  batch_size: 4096
  lr: 1.0e-3
  update_tqdm_freq: 1
  grad_accumulation_steps: 1
  logger:
    use_neptune: false
  optimizer: AdamW

  callbacks:
    save_best_model:
      enable: true
      freq: 500
slurm:
  time: 04-00:00:00
  partition: upex
  reservation: false
  chdir: '~/maxwell_output'
