name: "dummy_model2"
backend: "python"
max_batch_size: 1
input [
  {
    name: "curve"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "priors"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  }
]

output [
  {
    name: "params"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
    {
    name: "curve_predicted"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "sld_x_axis"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "sld_profile"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
]
